config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pets do 
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :destroy, :update]
  resources :dashboards, only: [:index]
  resources :profiles, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time
  validates :user_id, presence: true
  validates :pet_id, presence: true, uniqueness: {scope: :user_id}


  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  # association
  belongs_to :user
  has_many :bookings, dependent: :destroy

  # profile picture
  has_one_attached :photo
  
  # validations
  validates :user_id, presence: true
  validates :name, presence: true
  validates :price, presence: true

  # Pet Type
  def self.all_type
    %w(Dog Cat)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validation
  validates :name, presence: true

  # profile picture
  has_one_attached :photo

  # convert location to lat and lon
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  
  # association
  has_many :pets, dependent: :destroy
  has_many :bookings, through: :pets

  def self.pet_counter(id)
    Pet.where(user_id: id).count
  end

end
# Geocoder.search([-38.07, 145.355]).first.postal_code
# Geocoder.search("#{postal_code}, Australia").first

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:create, :new]

	def show
		@booking = Booking.find(params[:id])
	end
	
  def index 
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.total_price = total_price
    @booking.pet = @pet
    @booking.user = current_user
    if @booking.save
      redirect_to dashboards_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.offer_accepted
      @booking.offer_accepted = false
    else
      @booking.offer_accepted = true
    end
    @booking.save
    redirect_to dashboards_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to dashboards_path
    else
      render :new
    end
  end

  private

  def total_price
    start_time = booking_params[:start_time]
    end_time = booking_params[:end_time]
    start_time_booking = start_time.to_date
    end_time_booking = end_time.to_date
    ((end_time_booking - start_time_booking).to_i + 1) * @pet.price
  end

  def set_booking
    @pet = Pet.find(params[:pet_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time) 
  end

end
	

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @pets = current_user.pets
    # @booking_offers = current_user.bookings
    @booking_offers = Booking.all.select do |booking|
      booking.pet.user.id == current_user.id
    end 
    @my_bookings = Booking.where(user_id: current_user.id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    if params[:location].nil? || params[:location].empty?
      @pets = Pet.all
      @users = User.all
    else
      @pets = []
      @users = User.near("#{params[:location]}, Victoria, Australia", params[:distance].to_i, order: :distance)
      @users.each do |user|
        @pets << Pet.where(user_id: user.id)
      end
      @pets.flatten!
    end     
    pets_with_different_owner
    @markers = @users.geocoded.map do |user|  
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { user: user })
      }
    end 
  end
    
  def destroy
    @pets = Pet.find(params[:id])
    if @pets.destroy
      redirect_to pets_path
    else
      render pets_path 
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def new
    @pet = Pet.new
  end
  
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end
  
  def show
    @pet = Pet.find(params[:id])
  end

  private 

  def pet_params
    params.require(:pet).permit(:name, :description, :pet_type, :photo, :image_url, :price)
  end

  def pets_with_different_owner
    @pets = @pets.reject { |pet| pet.user_id == current_user.id}
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params) 
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :mobile, :location, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Booking</h1>

<div class="booking-body">
  
  <% if @bookings.empty? %>
    <h3 class="text-center">No Bookings</h3>
    <% else %>
  
  <ul>
    <% @bookings.each do |booking| %>
      <li class="list-unstyled">
        <div class="border d-flex flex-column w-50 align-items-center my-4 p-3">
          <p><strong>Booked by: </strong><%= booking.user.email %></p>
          <p><strong>Ordered pet: </strong><%= booking.pet.name %></p>
          <p><strong>Owned by: </strong><%= booking.pet.user.email.split("@").first.upcase %></p>
          <p><strong>Start date: </strong><%= booking.start_time.strftime("%Y-%m-%d") %></p>
          <p><strong>End date: </strong><%= booking.end_time.strftime("%Y-%m-%d") %></p>
          <p><strong>Total Price: </strong><%= booking.total_price %></p>   
          <p><strong><%= booking.offer_accepted ? 'ACCEPTED' : 'PENDING'%></strong></p>    
        </div>
      </li>
    <% end %>  
  </ul>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1 class="text-center my-3">Booking</h1>
<p class="text-center my-1 booking-pet__name"><%= @pet.name %></p>

<%= simple_form_for [@pet, @booking] do |f| %>
  <%= f.input:start_time, as: :date, min: Date.today, html5: true %>
  <%= f.input:end_time, as: :date, html5: true %>
  <p><strong>Price per day: $ <%= @pet.price %> </p> 
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>YOUR BOOKING</h1>
<%= link_to "Book", bookings_path %>

<ul>
  <li>
    <%= @booking.user.email %>
  </li>
  <li>
    <%= @booking.pet.name %>
  </li>
  <li>
    <%= @booking.total_price %>
  </li>
  <li>
    <%= @booking.start_time %>
  </li>
  <li>
    <%= @booking.end_time %>
  </li>
</ul>

app/views/dashboards/index.html.erb
<div class="container">
	<h1 class="text-center">
		<strong><%= current_user.name.upcase%></strong> Dashboard
	</h1>
		<div class="current-offers-heading-container">
			<h3 class="text-center">My Current Offer's</h3>
		</div>	

	<div class="offers-container">
			<% if @booking_offers.empty? %>
			<p>No Current Offer</p>
			<% else %>
				<% @booking_offers.each do |offer|%>
					<div class="border d-flex flex-column align-items-center my-2 pt-3 offers-card">
						<p>Renting pet: <%= offer.pet.name%></p>
						<p>Start date: <%= offer.start_time.strftime("%Y-%m-%d")%></p>
						<p>End date: <%= offer.end_time.strftime("%Y-%m-%d")%></p>
						<p>To User: <%= offer.user.email%></p>
						<p>Total amount: <%= offer.total_price%></p>
						
						<% if offer.offer_accepted %>
							<strong>ACCEPTED <%= link_to 'Change', booking_path(offer.id), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn-danger", reload: true %></strong>
						<% else %>
						<div>
							<%= link_to 'Accept', booking_path(offer.id), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn-success", reload: true%>
							<%= link_to 'Decline', booking_path(offer.id), method: :delete,  data: {confirm: "Are you sure this booking will be deleted?"}, class: "btn btn-danger", reload: true %>
						</div>
						<% end %>
						
					</div>
				<% end %>
			<% end %>
		</div>
	<div class="dashboard-bottom-container">
		<div class="bottom-pet-container">
			<h3 class="text-center">My Pets</h3>
			<div class="pet-container">
				<% if @pets.empty? %>
					<p>You don't have any pets</p>
				<% else %>
					<!-- <% @pets.each do |pet|%>
						<p><%= pet.pet_type %> 
							<%= link_to pet_path(pet.id) do %>
								<%= pet.name%></p>
							<% end %>
					<% end %>
					-->
					<div class="cards">
						<% @pets.each do |pet|  %>
							<%= render "shared/my_pet_card", pet: pet %>
						<% end %>
					</div>
				<% end %>
			</div>
			</div>
			<div class="bottom-bookings-container">
				<h3 class="text-center">Bookings</h3>
				<div class="bookings-container">
					<% @my_bookings.each do |booking|%>
						<%= link_to booking_path(booking.id) do %>
							<div class="border d-flex flex-column align-items-center p-2">
								<p>User Email: <%= booking.pet.user.email%></p>
								<p>Pet: <%= booking.pet.name%></p>
								<p>Start: <%= booking.start_time.strftime("%Y-%m-%d")%></p>
								<p>End: <%= booking.end_time.strftime("%Y-%m-%d")%></p>
								<p>Total price: <%= booking.total_price%></p>
								<div class="py-1">
									<%= link_to 'Delete', booking_path(booking.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
								</div>
							</div>
						<% end %>
					<% end %>
				</div>
			</div>
	</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>
      <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-image" style="background-image: url(https://images.unsplash.com/photo-1534361960057-19889db9621e?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8YW5pbWFsJTIwcnVufGVufDB8fDB8&ixlib=rb-1.2.1&w=1000&q=80);
   height: 90vh; mb ">
	<div class="container d-flex h-100 align-items-center">
	  <div class="mx-auto text-center">
	    <h1 mx-auto my-0 class="title">RENT A PET</h1>
			<h2 text-white-50 mx-auto mt-2 mb-5>Why wait get it today</h2>
			<% unless  user_signed_in? %>
				<div class="try_button">
					<%= link_to 'Try Us Now', new_user_registration_path, class: "btn btn-primary btn-lg", id: "front_button" %>
				</div>
			<% end %>	
		</div>
	</div>
</div>
 
<div class="cd-container container">
  <h2>Recently added pets</h2>
  <div class="row display: flex justify-content: space-evenly">
		<% Pet.all.last(3).each do |pet| %>
			<%= render 'shared/landing_page_card', pet: pet %>
		<% end %>
	</div>
</div>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :pet_type, as: :select, collection: Pet.all_type %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/pets/_infowindow.html.erb
<div class="popup-container">
  <p>Owner - <%= user.name.upcase %></p>
  <% if User.pet_counter(user.id).positive? %>
    <p>Pets - <%= User.pet_counter(user.id) %></p>  
  <% end %>
  <p>Location - <%= user.location.upcase %></p>
</div>

app/views/pets/edit.html.erb
<h1>Edit a Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<div class="container">
	<h1 class="text-center">RENT-A-PET</h1>
	<div>
		<%= render 'shared/search_bar' %>
	</div>
	<div class ="info_container">
		<div class="cards">
			<% @pets.each do |pet|  %>
				<%= render "shared/card_detail", pet: pet %>
			<% end %>
		</div>
		<div id="map"
				style="width: 500px; height: 650px;"
				data-markers="<%= @markers.to_json %>"
				data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
		</div>
	</div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <%= render 'form'%>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h1><strong>Pet Name</strong> <%= @pet.name %></h1>
  <p><strong>Descriptions:</strong> <%= @pet.description %></p>
  <p><strong>Animal Type</strong> <%= @pet.pet_type %></p>
  <% if @pet.photo.attached? %>
    <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill, class: "img-thumbnail" %>  
  <% end %>
  <p><strong>Pet owner email</strong> <%= @pet.user.email %></p>
  <p><strong>Price</strong> $ <%= @pet.price %></p>
  <div>
    <% if current_user.id == @pet.user.id %>
      <%= link_to 'DELETE ME', pet_path, method: :delete, data: {confirm: "Are you sure? :'("} %>
      <%= link_to 'EDIT ME', edit_pet_path %>      
    <% else %>
      <%= link_to 'ADD BOOKING', new_pet_booking_path(@pet) %>
    <% end %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= simple_form_for @user, url: profile_path(@user.id) do |f| %>
  <%= f.input :name %>
  <%= f.input :mobile %>
  <%= f.input :location %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/profiles/edit.html.erb
<h1>User Profile</h1>

<%= render 'form'%>

app/views/shared/_alerts.html.erb
<div class="notice">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
</div>

app/views/shared/_card_detail.html.erb
<div class="card">
	<div class="card-row no-gutters">
		<div class="col-sm-4 m-0">
			<% if pet.photo.attached? %>
				<%= cl_image_tag(pet.photo.key) %>
			<% else %>
				<%= cl_image_tag('https://res.cloudinary.com/dddsdfpy5/image/upload/v1614909966/default_profile_REP_niiyts.jpg') %>
			<% end %>
		</div>
		<div class="col-sm-8 card-body">
			<div class="card-headers">
				<h3><%= pet.name %></h3>
				<p><%= pet.user.location %></p>
			</div>
			<p class="card-description"><%= pet.description %></p>
			<div class="card-bottom">
				<%= link_to 'Rent Pet', pet_path(pet), class: "card-link" %>
				<p class="text-muted">$ <%= pet.price %> / day</p>
			</div>
		</div>
	</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Rent a pet today or regret tomorrow <i class="fas fa-heart"></i> at Inspire 9
  </div>
</div>

app/views/shared/_landing_page_card.html.erb
<div class="card" id="cards" style="width: 18rem;">
  <div class="card-img-top" >
    <% if pet.photo.attached? %>
      <%= cl_image_tag(pet.photo.key, height: 250, width: 286, crop: :fill)%>
    <% else %>
      <%= cl_image_tag('https://res.cloudinary.com/dddsdfpy5/image/upload/v1614909966/default_profile_REP_niiyts.jpg', height: 250, width: 286, crop: :fill) %>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= pet[:name] %></p> 
  </div>
</div>

app/views/shared/_my_pet_card.html.erb
<div class="card">
	<div class="card-row no-gutters">
		<div class="col-sm-4 m-0">
			<% if pet.photo.attached? %>
				<%= cl_image_tag(pet.photo.key) %>
			<% else %>
				<%= cl_image_tag('https://res.cloudinary.com/dddsdfpy5/image/upload/v1614909966/default_profile_REP_niiyts.jpg') %>
			<% end %>
		</div>
		<div class="col-sm-8 card-body">
			<div class="card-headers">
				<h3 class="mx-auto"><%= pet.name %></h3>
			</div>
			<p class="card-description"><%= pet.description %></p>
			<div class="card-bottom">
				<%= link_to 'Edit Pet', pet_path(pet), class: "card-link" %>
				<p class="text-muted">$ <%= pet.price %> / day</p>
			</div>
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar">
    <div class="container">
    
      <div class="logo">
        <%= image_tag 'https://res.cloudinary.com/dddsdfpy5/image/upload/v1614644263/Orange_and_White_Dog_Walking_Service_Logo_flb6pz.png' %>
      </div>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Find Pets', pets_path %></li>
        <li><%= link_to 'Dashboard', dashboards_path %></li>
				<li>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name.upcase %>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <%= link_to 'Profile', edit_profile_path(current_user.id), class: "dropdown-item" %>
              <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to 'Bookings', bookings_path, class: "dropdown-item" %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </li>
				<!--
					<li class="img-circle-container">
						<% if current_user.photo.attached? %>
							<%= cl_image_tag current_user.photo.key, class: "img-profile"%> 
						<% else %>
							<%= cl_image_tag 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png', class: 'img-profile' %>
						<% end %>
					</li>
				-->
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= link_to 'Add Pet', new_pet_path, class: "btn btn-info" %>
    <form class="d-flex flex-grow-1" action=<%= pets_path %> method="GET">
      <select class="form-control" id="sel1" name="distance">
        <option value=10>Within 10 kms</option>
        <option value=20>Within 20 kms</option>
        <option value=50>Within 50 kms</option>
        <option value=100>Show All</option>
      </select>
      <input class="form-control me-2" name="location" type="search" placeholder="Enter your Australian postcode" aria-label="Search" value="<%= params[:location]%>">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>

  